
# values.yaml

# Image configuration
image:
  repository: "faisalkhan35/my-war-app"
  tag: "latest"

# Resources configuration
resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "250m"
