
# deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-war-app
  labels:
    app: war-app
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: war-app
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: war-app
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: war-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "{{ .Values.resources.requests.memory }}"
            cpu: "{{ .Values.resources.requests.cpu }}"
          limits:
            memory: "{{ .Values.resources.limits.memory }}"
            cpu: "{{ .Values.resources.limits.cpu }}"
